### ISSUE TITLE
Still not able to see multiple events on the same venu

### ISSUE THREAD

**Issue by elipsius** [mt-support/tribe-ext-map-show-all-events-with-same-venue#4]
Installed 1.1 today on:
The Events Calendar Pro 4.5.1
Events Calendar 4.7.2
Word Press:  4.9.9

I see the map but only one event per venue is shown, extension is installed and activated.

**Comment by cliffordp** [comment]
Thanks for the details, but this is not the support channel for this extension. Please report the issue to https://support.theeventscalendar.com/

Thank you.
